### ISSUE TITLE
World wide total

### ISSUE THREAD

**Issue by todoneunl** [lachhebo/corona-tracker#4]
Is it possible to add the world wide total of the various numbers?

**Comment by lachhebo** [comment]
yeah, it is a good idea but i don't think the API used here is giving us this information

**Comment by lachhebo** [comment]
Hi, 
 
It is possible by using the API with the parameter all instead of the name of a specific country : 

 - https://corona.lmao.ninja/all 

We could create a new value in the list called world and make this specific call instead of the country one based, it is three lines of code if you want to do it ;)

**Comment by todoneunl** [comment]
@lachhebo Great! I'm not a developer, so I'm afraid I can't help you that much with this. But I'm glad you found something and I'm looking forward to the updated extension. Thanks!

**Comment by lachhebo** [comment]
Haha, don't worry, i think i will have time to do it before the end of the week. 

You're welcome.

**Comment by todoneunl** [comment]
Thanks! I trust your attentions of course, so I can close the issue. Good luck! And stay well in these times. :fist_raised:
